[build]
target = "thumbv7em-none-eabi"

[target.thumbv7em-none-eabi]
runner = "probe-rs run --connect-under-reset --chip STM32F302CBTx"
rustflags = ["-C", "link-args=-Tlink.x -Tdefmt.x"]
# all provided by dependencies - black magic => what do they do, where are they documented?

[env]
DEFMT_LOG = "info" # trace is lowest logging level - higher ones automatically enabled
# https://defmt.ferrous-systems.com/filtering.html
# for now using info as logs were getting quite verbose
# IMPORTANT; for changes here to propagate must run `cargo clean`